name: winsys
description: winsys project
version: 2025.426.2009
homepage:
repository: https://github.com/dart-pkg/winsys
environment:
  sdk: ^3.7.2
platforms:
  #android:
  #ios:
  #linux:
  #macos:
  #web:
  windows:
dependencies:
  dynamic_function: ^1.0.4
  ffi: ^2.1.4
  std: ^2025.426.1637
  sys: ^2025.426.1725
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
