name: "winsys"
description: "winsys project"
version: "2025.422.1854"
homepage: null
repository: "https://github.com/dart-pkg/winsys"
environment:
  sdk: "^3.7.2"
dependencies:
  dynamic_function: ^1.0.4
  ffi: ^2.1.4
  misc: ^2025.422.1753
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.6
  test: ^1.25.15
