name: winsys
description: winsys project
version: 2025.424.759
homepage:
repository: https://github.com/dart-pkg/winsys
environment:
  sdk: ^3.7.2
platforms:
  #android:
  #ios:
  #linux:
  #macos:
  #web:
  windows:
dependencies:
  dynamic_function: ^1.0.4
  ffi: ^2.1.4
  misc: ^2025.424.118
  sys: ^2025.424.246
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
