name: winsys
description: winsys package project
version: 2025.420.529
homepage:
repository: https://github.com/dart-pkg/winsys

environment:
  sdk: ^3.7.2

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.15
  embed: ^1.4.1
  lints: ^5.1.1
  output: ^1.0.1
  test: ^1.25.15
