name: winsys
description: winsys project
version: 2025.503.20
homepage: 
repository: https://github.com/dart-pkg/winsys
environment:
  sdk: ^3.7.2
platforms:
  # android:
  # ios:
  # linux:
  # macos:
  # web:
  windows: 
dependencies:
  dynamic_function: ^2025.427.1341
  ffi: ^2.1.4
  std: ^2025.502.2358
  sys: ^2025.503.6
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.502.1958
  test: ^1.25.15
